server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8005
  servlet:
    context-path: /

spring:
  profiles:
    #??application-common.yml??
    include: common
  application:
    name: order_service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.33.247.199:3307/drivemate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: abc123456
      initial-size: 4
      max-active: 8
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 1
  redis:
    database: 6
    host: 101.33.247.199
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  cloud:
    inetutils:
      #??????Nacos??IP??
      preferred-networks: 101.33.247.199
    nacos:
      #??????Web??????????
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        server-addr: 101.33.247.199:8848
        prefix: ${spring.application.name}
        namespace: drivemate
      #??????Nacos??????
      discovery:
        namespace: drivemate
        username: nacos
        password: nacos
        server-addr: 101.33.247.199:8848
        heart-beat-interval: 1000
        heart-beat-timeout: 1000
        group: DEFAULT_GROUP
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

tx-lcn:
  client:
    #??TM??
    manager-address: 127.0.0.1:8070

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 300000