server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8201
  servlet:
    context-path: /

spring:
  application:
    name: gateway
  cloud:
    inetutils:
      preferred-networks: 101.33.247.199
    nacos:
      #????
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        server-addr: 101.33.247.199:8848
        prefix: ${spring.application.name}
        namespace: drivemate
      discovery:
        namespace: drivemate
        username: nacos
        password: nacos
        server-addr: 101.33.247.199:8848
        heart-beat-interval: 1000
        heart-beat-timeout: 1000
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: 101.33.247.199:8719
    gateway:
      discovery:
        locator:
          enabled: false
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许的跨域ip
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://172.29.194.239:3000"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 本次跨域检测的有效期
      routes:
        - id: bff_driver
          uri: lb://bff-driver
          predicates:
            - Path=/driver/**
          filters:
            - StripPrefix=1
        - id: mis
          uri: lb://mis
          predicates:
            - Path=/mis/**
          filters:
            - StripPrefix=1
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
feign:
  sentinel:
    enabled: true

management:
  # ??????????
  endpoints:
    web:
      exposure:
        include: "*"


