spring:
  profiles: common

tencent:
    cloud:
        appId: "1318932019"
        secretId: "AKIDRmwlPr43rTsqeGfrpcDZkmgPuENMq9HD"
        secretKey: "nPr8B1e6MSM1WWl4Mapx20ueIk16xZAY"
        region-public: "ap-guangzhou"
        bucket-public: "dm-public-1318932019"
        region-private: 'ap-guangzhou'
        bucket-private: 'dm-private-1318932019'
        face:
          groupName: DriveMate
          region: ap-guangzhou

wx:
    app-id: "wx91c8f3579efcb95b"
    app-secret: "42808f2cb1dcc718f36ff4f5b11f0054"
    mch-id: "1526972031"
    key: "qv9Kihy5TOJxGySzFO8pd4wCMg3tn6YK"
    cert-path: "C:/Users/32125/Desktop/apiclient_cert.p12"

minio:
    endpoint: "http://101.33.247.199:9000"
    access-key: "root"
    secret-key: "abc123456"