spring:
  profiles: common

tencent:
    cloud:
        appId: "1318932019"
        secretId: "腾讯云Id"
        secretKey: "腾讯云密钥"
        region-public: ""
        bucket-public: ""
        region-private: ''
        bucket-private: ''
        face:
          groupName: 
          region: 

wx:
    app-id: ""
    app-secret: ""
    mch-id: ""
    key: ""
    cert-path: ""

minio:
    endpoint: ""
    access-key: ""
    secret-key: ""
